// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.DataAccesLayer;

namespace ProductService.Migrations
{
    [DbContext(typeof(TGDbContext))]
    partial class TGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProductService.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oyun Bilgisayarları"
                        },
                        new
                        {
                            Id = 2,
                            Name = "İş Bilgisayarları "
                        });
                });

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Tulpar T7 V22.2 17,3 Gaming Laptop",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Tulpar T7 V25.1.2 17,3 Gaming Laptop",
                            Price = 0m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Casper Excalibur G770.1140-8EL0T-B",
                            Price = 0m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Asus ROG Strix G513IE-HN065",
                            Price = 0m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "MSI Katana GF76 11UE-414TR ",
                            Price = 0m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "MSI Bravo 15 B5DD-209XTR",
                            Price = 0m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Apple MacBook Air M1",
                            Price = 0m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Apple MacBook M1 Pro",
                            Price = 0m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Apple MacBook Pro M2",
                            Price = 0m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Apple MacBook Air M2 ",
                            Price = 0m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Apple MacBook Pro",
                            Price = 0m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Asus Zenbook Pro",
                            Price = 0m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Dell M7760 TKNM7760RKS55M09 W-11955M",
                            Price = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
